spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  session:
    #If a duration suffix is not specified, seconds is used.
    timeout: 3600
    redis:
      # Namespace for keys used to store sessions.
      namespace: "spring:oauthsession"

server:
  port: 9090
