zuul:
  routes:
    #这里没有使用服务发现组件，所以将服务服务地址写死
    token:
      url: http://localhost:9090
    order:
      url: http://localhost:9080
  #客户端发过来的 http头 不往后转发 设置成空 就是所有的 header都向后转发
  #zuul.sensitiveHeaders设置为空，代表不过滤任何Header信息，Header会向下转发
  sensitive-headers:
  ratelimit:
    enabled: false
    # 生产环境应使用 redis
    repository: jpa
    defaultPolicyList:
      # 时间窗口内最多有几个请求
      - limit: 2
        # 这些请求加在一起消耗的时间是多少
        quota: 1
        # 时间窗口 5s
        refresh-interval: 15
        type:
          - url
          - httpmethod
    policyList:
      # 配置以token开头的请求
      token:
      - limit: 2 #可选 - 每个刷新时间窗口对应的请求数量限制
        quota: 1 #可选-  每个刷新时间窗口对应的请求时间限制（秒）
        refresh-interval: 3 # 刷新时间窗口的时间，默认值 (秒)
        type: #可选 限流方式
          - url
          - httpmethod
          - origin
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 9070
